document.getElementById("mood-submit-btn").addEventListener("click", submitMood);

function submitMood() {
    const mood = document.getElementById("mood-select").value;
    const moodLevel = document.getElementById("mood-level").value;

    if (mood.trim() !== "") {
        displayMotivationalMessage(mood, moodLevel);
    } else {
        alert("Please select your mood before submitting.");
    }
}

// Function to Display Motivational Message
function displayMotivationalMessage(mood, moodLevel) {
    const adviceSection = document.getElementById("mood-advice-section");
    const adviceMessage = document.getElementById("mood-advice-message");

    // Motivational messages categorized by mood and intensity
    const motivationalMessages = {
        happy: [ 
            "Stay awesome! Your happiness is contagious, spread it around!",
            "Remember, happiness is a journey, not a destination. Keep going!",
            "You're glowing today! Let your smile change the world!",
            "Enjoy every moment, you deserve all the good things happening to you.",
            "Life is beautiful because you make it that way!",
            "Your positive energy radiates, bringing joy to those around you.",
            "Happiness suits you well. Keep smiling and brighten up everyone’s day!",
            "Cherish this joy, it’s the little things that make life wonderful.",
            "You’re like a ray of sunshine today; keep spreading that light.",
            "You’re a walking source of happiness! Don’t let anything dim that glow.",
            "Let your joy inspire others to find their own happiness.",
            "Today, make happy memories that you’ll treasure forever.",
            "A joyful heart attracts beautiful moments and wonderful people.",
            "Savor each happy moment, they create a life worth remembering.",
            "You’re overflowing with positivity; it’s truly inspiring!",
            "Spread kindness and happiness today; it’s a gift to yourself and others.",
            "Your smile is a powerful force; use it to uplift the world.",
            "Happiness radiates from within you, touching everyone around.",
            "Your joy is a breath of fresh air to everyone you meet.",
            "Every day has something good; today is filled with your happiness.",
            "Enjoy the small victories and big joys that come your way.",
            "Hold on to this happiness; it’s a sign of great things ahead.",
            "Today is beautiful, just like you. Keep embracing that happiness!",
            "Happiness is a choice, and you’re choosing it beautifully.",
            "Let your heart be light and let go of any worries.",
            "Your happiness is the best gift you can give to the world.",
            "There’s something magical about your smile; it’s truly uplifting.",
            "Cherish today’s happiness and let it fuel you for tomorrow.",
            "Let the world see your joy; it’s truly inspiring and refreshing.",
            "Life feels brighter when you’re happy. Keep sharing that light!",
            "Your happiness is your power; embrace it fully today.",
            "Your joyful presence makes a difference to everyone you meet.",
            "Smile wide, laugh loud, and live in the moment. Today is yours!",
            "Let your happiness be a reflection of your beautiful soul.",
            "Happiness is contagious; thanks for spreading it everywhere you go.",
            "Keep smiling, your happiness lights up the world!",
            "Every happy moment counts; make today unforgettable.",
            "You’re a beacon of positivity; keep shining brightly.",
            "Happiness is within you; it’s what makes you truly amazing.",
            "Your joy is a testament to the beauty of life. Embrace it!",
            "Today’s a great day to be happy. Let that happiness grow!",
            "Nothing can dim the happiness in your heart; let it shine!",
            "You’re like a magnet for good vibes today. Enjoy every second!",
            "May your day be as wonderful as your smile.",
            "Happiness looks good on you; wear it proudly today.",
            "Remember, happiness grows when shared. Spread it far and wide.",
            "Life is happier when we focus on what brings us joy.",
            "Smile freely, laugh often, and enjoy the journey today.",
            "Your happy spirit is the best part of today!",
            "Let your happiness be your compass, guiding you to great places.",
            "Happiness is a gift you’re sharing with the world. Thank you!"        
        ],
        sad: [
            "It's okay to feel sad sometimes. Take deep breaths, this too shall pass.",
            "You are stronger than you think. Every storm runs out of rain.",
            "You are not alone; things will get better. Just take it one step at a time.",
            "Feeling down is natural. Take time to rest and be kind to yourself.",
            "Remember, after the rain comes the rainbow. You will feel better soon.",
            "Even in darkness, light will find its way to you. Hold on.",
            "Take things slowly. Healing is a process, and it’s okay to take your time.",
            "Your feelings are valid; give yourself permission to feel them.",
            "Sadness doesn’t last forever. Brighter days are ahead.",
            "You’re not defined by this moment. Brighter days are on the way.",
            "Allow yourself to rest. Sometimes the best way to heal is to pause.",
            "Every tear is a step toward healing. Take all the time you need.",
            "It’s okay to ask for help. You don’t have to face everything alone.",
            "Even if today is hard, know that tomorrow is a new chance.",
            "Take a deep breath and remind yourself of your strength.",
            "You’re allowed to take a break. You don’t have to do it all right now.",
            "This feeling is temporary. You will rise above it in time.",
            "You’re brave for facing what you’re feeling. It’s okay to feel.",
            "Healing is not linear; allow yourself to move at your own pace.",
            "Sadness is a part of life, but it’s not the whole story.",
            "You are resilient, even if you don’t feel it right now.",
            "You don’t have to be strong all the time. It’s okay to be vulnerable.",
            "Take a moment to breathe. This moment will pass.",
            "Allow yourself to feel. Suppressing sadness doesn’t make it go away.",
            "You are worthy of love and kindness, especially from yourself.",
            "Remember, you’ve overcome hard times before. You can do it again.",
            "In time, this pain will ease. Be patient and gentle with yourself.",
            "Take it one day at a time. Healing takes patience.",
            "Allow yourself to be human. We all have difficult days.",
            "Your feelings are real, but they don’t define your worth.",
            "Lean into the support around you. You’re not alone in this.",
            "Give yourself the kindness you would offer to a friend.",
            "Sometimes it’s okay to not be okay. Let yourself feel.",
            "You are not broken. Sadness is a part of being human.",
            "It’s okay if all you did today was hold yourself together.",
            "Be gentle with yourself today. Healing doesn’t happen overnight.",
            "You have a strength that sadness can’t take away.",
            "This moment doesn’t define you. There are brighter days ahead.",
            "Just because you’re struggling doesn’t mean you’re failing.",
            "Take comfort in knowing this feeling won’t last forever.",
            "Healing takes time. Give yourself the space to recover.",
            "Remember, it’s okay to seek support. You’re not alone.",
            "Sadness is temporary, but your resilience is everlasting.",
            "One step at a time, you’re moving toward healing.",
            "Sometimes the best thing you can do is just breathe.",
            "You’re allowed to take your time. Healing is a process.",
            "Your sadness is a small part of a beautiful, complex story.",
            "Take comfort in knowing it’s okay to feel this way.",
            "You are not your sadness; you are so much more.",
            "Allow yourself the time you need. Healing comes in waves.",
            "This sadness is temporary; joy will find you again."             
        ],
        anxious: [
            "Focus on your breathing. You are safe, and things will work out.",
            "Take things one moment at a time. You've faced challenges before, and you can do it again.",
            "You are capable of handling whatever comes your way. Trust yourself.",
            "It's okay to take a break and collect your thoughts. You're doing great.",
            "You've got this! Remember, your worries are only thoughts, not reality.",
            "Anxiety is just a feeling. It will pass, and you will find calm again.",
            "You are in control. Focus on what you can do right now, in this moment.",
            "Breathe deeply. Each breath brings you a little closer to peace.",
            "Give yourself permission to pause. Take things one step at a time.",
            "It’s okay to feel anxious. Let it come and let it go; you are still strong.",
            "You are safe. Breathe, relax, and remember you are in control.",
            "Take small steps. You don’t have to face everything all at once.",
            "Anxiety does not define you; it’s a moment that will pass.",
            "Find a quiet space, breathe, and focus on one peaceful thought.",
            "Trust that you have handled things before, and you can do it again.",
            "Let go of perfection. Just do your best; that is enough.",
            "It’s okay to feel this way. You are allowed to take your time.",
            "Remember, you don’t have to figure everything out right now.",
            "You are more than your anxious thoughts. Let them pass by.",
            "Take things slowly. You are doing better than you realize.",
            "Your peace is within you. Trust that calm will return.",
            "Every small breath brings a little more peace. You are okay.",
            "You are allowed to ask for help. Support is there for you.",
            "Focus on the present. Let go of tomorrow; just be here now.",
            "Remember that feelings are temporary, even this anxious moment.",
            "Be kind to yourself. You are doing your best, and that is enough.",
            "Release your tension, one breath at a time. Peace is on its way.",
            "You are not alone in this. Many have felt what you feel and found calm.",
            "Your mind may race, but your heart knows you will be okay.",
            "Each breath brings a little more relief. Keep breathing slowly.",
            "Focus on one small task at a time. It’s okay to take it slow.",
            "You are resilient, even if you feel shaky right now.",
            "There is strength in taking a step back and breathing.",
            "These thoughts will pass; they do not control you.",
            "Trust in yourself. You’ve come this far, and you’ll get through this.",
            "Allow yourself to let go of what you cannot control.",
            "Focus on your surroundings. Feel grounded; you are safe here.",
            "Let each breath remind you that you are steady and secure.",
            "You are learning to find calm, even in anxious moments.",
            "It’s okay to feel uncertain. Clarity will come in time.",
            "Release the need for answers. Just let yourself be for a moment.",
            "You’ve made it through difficult days before. This too shall pass.",
            "Slow down, breathe deeply, and know you are okay right now.",
            "It’s okay if you need extra support. You are not alone in this.",
            "Give yourself time to adjust. There is no rush to be okay.",
            "Trust that you have the strength to calm your mind and heart.",
            "You are learning to be resilient in the face of uncertainty.",
            "It’s okay to not be okay sometimes. Let yourself feel, then release.",
            "Remind yourself of things that bring you peace. They are within reach.",
            "Breathe, relax your shoulders, and remember you are safe.",
            "Your peace is always within you, even if it feels distant right now."
        ],
        angry: [
            "Take a moment to pause. Deep breaths can help calm the storm inside.",
            "You deserve peace. Find your center, and let go of what’s upsetting you.",
            "Channel your energy into something positive. You are in control.",
            "Anger is temporary. Give yourself time, and you’ll regain clarity.",
            "Remember, you can choose to respond calmly. Let peace guide you.",
            "Release the tension with a deep breath. Calmness is within reach.",
            "Take a step back; sometimes a fresh perspective can ease frustration.",
            "Let go of what you cannot control and focus on your inner peace.",
            "Allow yourself to feel, but let anger pass through, not stay.",
            "Count to ten, breathe, and let calm return to you.",
            "Inhale deeply, exhale slowly. Let peace fill the space inside you.",
            "Remember, your peace is more important than the moment of anger.",
            "It’s okay to feel upset. Take time to cool down at your own pace.",
            "Find something calming to focus on. Let it ground you.",
            "You have the power to let go. Breathe out the frustration.",
            "Pause, breathe, and let the anger slowly drift away.",
            "Walk away if you need to. Your peace matters more than this moment.",
            "Replace anger with patience. You are stronger than this feeling.",
            "Letting go of anger is a gift you give to yourself.",
            "You’re in control of how you respond. Choose calmness over chaos.",
            "Release the tension in your shoulders. Breathe and find your center.",
            "Take a break, step outside, and let nature soothe your mind.",
            "Anger is a visitor; it doesn’t have to stay.",
            "Give yourself space to cool off. You’ll feel better soon.",
            "Focus on calming thoughts. Peace is just a breath away.",
            "Let the anger dissolve as you exhale slowly and deeply.",
            "Allow your mind to find stillness; this moment will pass.",
            "Your calm response is a sign of your strength.",
            "Visualize releasing your anger, letting it float away.",
            "It’s okay to feel mad, but let it be temporary, not permanent.",
            "You can’t change everything, but you can change how you feel.",
            "Anger can’t control you unless you let it. Breathe through it.",
            "You are in charge of your emotions, not the other way around.",
            "Let go of what’s out of your hands; peace is within your reach.",
            "Take a few deep breaths; each one brings you closer to calm.",
            "Focus on what makes you feel grounded. Let anger drift away.",
            "Breathe in peace, breathe out anger. You’re finding your calm.",
            "Let go of what doesn’t serve your peace of mind.",
            "Shift your energy to something positive. You have that power.",
            "Anger will fade; your peace will stay. Focus on the latter.",
            "Choose peace over anger, even if it takes time to settle.",
            "You are stronger than this moment. Let calmness guide you.",
            "Walk it off, breathe, and let clarity replace frustration.",
            "Your peace is worth more than any temporary anger.",
            "Focus on solutions, not frustrations. Calm will follow.",
            "Forgive yourself for feeling angry; you’re human. Let it go.",
            "Take things slow. Sometimes a little patience eases a lot of anger.",
            "Visualize your anger melting away with each exhale.",
            "You have the strength to turn anger into calm and patience.",
            "Let your heart relax, your mind clear, and let peace in.",
            "Release the grip of anger and welcome a sense of ease."        
        ],
        calm: [
            "Cherish the calm moments; they are gifts to your soul.",
            "Your peacefulness inspires others around you. Stay centered.",
            "Enjoy the stillness and carry this tranquility throughout your day.",
            "You are in harmony with yourself. Let your inner calm shine.",
            "The calmness you feel is your superpower. Stay relaxed and keep smiling.",
            "Embrace this serenity; it nurtures your mind and soul.",
            "Your calm energy is like a soothing balm for the world.",
            "Hold on to this peace and let it carry you through anything.",
            "In this calm, you’ll find clarity and strength for what lies ahead.",
            "Your inner peace radiates outward, creating a ripple of tranquility.",
            "Take in this peaceful moment; it’s a gift to yourself.",
            "The calm you feel now will fuel you for whatever comes next.",
            "Breathe in peace, breathe out any remaining tension.",
            "You’re exactly where you need to be. Stay in this peaceful moment.",
            "This calmness is a reflection of your inner strength and balance.",
            "The world feels lighter when you’re centered and at ease.",
            "Inhale deeply, exhale slowly, and let this calmness expand within you.",
            "Your heart and mind are in perfect harmony. Hold on to that feeling.",
            "This calm is your foundation. Carry it with you always.",
            "Feel grounded in this moment of peace; it’s where your strength lies.",
            "Let this stillness recharge your spirit and bring you joy.",
            "Your mind is clear, your heart is calm, and your spirit is free.",
            "Stay rooted in this moment; your peace is unwavering.",
            "Your calm energy is a reminder of the beauty of simplicity.",
            "Embrace this serenity, for it is a reflection of your true self.",
            "Feel the beauty in this calm; it’s a moment just for you.",
            "Let this calmness stay with you, guiding you gently forward.",
            "In calmness, you’ll find answers and a sense of completeness.",
            "This moment of peace is yours to cherish and revisit anytime.",
            "You are in a sanctuary of calm; nothing can disturb your peace.",
            "This calmness is your inner strength; let it carry you onward.",
            "Find comfort in the quiet. Your spirit is at rest.",
            "Let this calmness deepen, nourishing every part of you.",
            "You are one with this moment, complete and at peace.",
            "This tranquility brings balance, clarity, and resilience.",
            "Stay in this space of calm; it is your center and your strength.",
            "The peace you feel now is a gift. Treasure it fully.",
            "Let the calm flow through you, creating stillness in every cell.",
            "This moment of peace is your safe haven; rest here as long as you need.",
            "Enjoy the gentleness of this moment; you are in a state of pure calm.",
            "Your calm presence is a powerful force of love and understanding.",
            "Hold on to this calm, it’s a reminder of your resilience and grace.",
            "This peaceful state is yours; let it fill your heart and mind.",
            "Your calmness is like a gentle river, flowing with grace and ease.",
            "Feel anchored in this calm, knowing it is always within you.",
            "Let your thoughts settle like leaves on a still pond.",
            "This moment is yours; let its calmness restore your spirit.",
            "Breathe in peace, exhale any worry; you are safe in this calm.",
            "Let this tranquility guide you, bringing clarity and purpose.",
            "Enjoy the fullness of this peaceful moment; it’s a gift to yourself.",
            "Feel the calm deepen with each breath; this is your sanctuary."        
        ],
        excited: [
            "Your excitement is electrifying! Use it to conquer your goals today!",
            "You have so much potential! Keep riding the wave of enthusiasm!",
            "Great things are coming your way. Keep the excitement alive!",
            "Let your excitement propel you forward. You’re doing amazing things!",
            "Harness your excitement; it's a sign you're passionate and capable!",
            "This energy is powerful. Use it to fuel your dreams and goals!",
            "Your enthusiasm is inspiring. Let it guide you toward success!",
            "Keep the momentum going; this excitement is a gift!",
            "Today is yours! Embrace this excitement and make it memorable.",
            "Your excitement is contagious! Spread the joy and positivity!",
            "Believe in your excitement; it’s a signal that great things are near.",
            "Let this excitement drive you to make your dreams a reality.",
            "You’re glowing with enthusiasm! Keep shining and inspiring others.",
            "Your energy is boundless. Keep pushing forward with confidence!",
            "Excitement looks good on you! Let it lead you to new adventures.",
            "This is your moment! Let the excitement carry you forward.",
            "Every step you take with excitement brings you closer to greatness.",
            "Today is filled with opportunities; let your excitement guide you.",
            "You’re on fire today! Use this energy to achieve your best.",
            "The world needs your enthusiasm. Keep it alive and share it widely!",
            "Let your excitement be the fuel that drives you toward your dreams.",
            "Your excitement is powerful; it’s a sign you’re on the right path.",
            "Let this enthusiasm remind you of your passion and purpose.",
            "This is just the beginning; amazing things are coming your way!",
            "You’re unstoppable when you’re excited. Keep moving forward!",
            "Use this energy to push beyond your limits and achieve greatness.",
            "Your excitement opens doors to new possibilities. Embrace it fully!",
            "You’re buzzing with potential! Let your excitement pave the way.",
            "Let your heart race with excitement; it’s leading you to greatness.",
            "Your excitement is the spark that lights up your path forward.",
            "Harness this energy to make today truly unforgettable.",
            "Feel the thrill of possibility! This excitement is your power.",
            "Your enthusiasm is like a magnet for good things. Keep it up!",
            "You’re in alignment with your passions; let the excitement flow.",
            "Celebrate this moment of excitement; it’s a sign of wonderful things.",
            "Let your excitement inspire others to pursue their dreams, too.",
            "The sky’s the limit! Keep soaring with this amazing energy.",
            "You’re on the path to success! Let your excitement lead the way.",
            "This energy is your superpower. Use it to make a difference today.",
            "Your excitement is a force; let it drive you to incredible places.",
            "Great things happen when you follow your excitement and passion.",
            "This is the start of something amazing; keep the momentum going!",
            "Feel the thrill of achieving your dreams. It’s closer than you think!",
            "Your excitement is proof that you’re doing what you love.",
            "Let your excitement bring new opportunities and adventures.",
            "You’re filled with potential; let your excitement unleash it all!",
            "Your excitement is a gift; use it to inspire yourself and others.",
            "This energy is your guide to new and thrilling experiences.",
            "Today is a day of endless possibilities. Go after them with joy!",
            "Your excitement fuels your creativity. Let it lead you to success!",
            "Keep this excitement alive; it’s the key to unlocking your dreams."        
        ],
        tired: [
            "Rest is important. Take care of yourself and recharge when needed.",
            "You deserve a break. Relax, refresh, and you’ll be back stronger.",
            "Give yourself permission to rest. Your body and mind need it.",
            "It’s okay to feel tired. Rest up, and tomorrow is a new chance.",
            "Take it easy today, your well-being matters. Recharge, you've earned it.",
            "Listen to your body; it’s okay to slow down and take a pause.",
            "A good rest today can set you up for a better tomorrow.",
            "Remember, taking a break doesn’t mean giving up. Rest and recharge.",
            "Your energy will return. Give yourself the gift of rest today.",
            "Allow yourself to feel tired. Rest is part of the journey, too.",
            "Sometimes the best thing you can do is to simply rest and reset.",
            "Be gentle with yourself; recovery takes time and self-care.",
            "Take time to rest without guilt. You’ve earned it.",
            "Your body is asking for rest. Listen, and give it the care it needs.",
            "Rest now so you can rise stronger later.",
            "You’re doing your best; it’s okay to pause and regain your energy.",
            "Let today be a day of rest, reflection, and gentle self-care.",
            "Fatigue is just your body asking for a break. Give it the rest it deserves.",
            "A little rest now can go a long way toward feeling better.",
            "Sometimes the most productive thing you can do is rest.",
            "You’re allowed to take time for yourself. Rest and recharge.",
            "Pause and let your energy return naturally; you’ve got this.",
            "Taking care of yourself includes taking a well-deserved break.",
            "Today is a good day to slow down and nurture your well-being.",
            "Your body deserves kindness and rest. Give yourself that gift today.",
            "You are worth the time it takes to recover and feel renewed.",
            "A rested body leads to a refreshed mind. Rest up today.",
            "It’s okay to step back. Your goals will be there when you’re ready.",
            "Allow yourself to relax; a little break can make all the difference.",
            "A peaceful rest today will give you the strength you need tomorrow.",
            "Recharging isn’t a waste of time; it’s essential for growth.",
            "Today, let your body and mind enjoy the calm of restful moments.",
            "You don’t have to do it all today. Rest and take it slow.",
            "Remember, even small breaks can renew your energy.",
            "Let go of any stress and focus on recharging yourself fully.",
            "Your body knows what it needs. Listen and give it the rest it deserves.",
            "Take time to nurture yourself; rest is essential for a balanced life.",
            "It’s okay to not have energy for everything. Focus on rest today.",
            "Give yourself a moment to breathe, relax, and recharge.",
            "Today, let rest be your priority. Tomorrow is a fresh start.",
            "Honor your need for rest; it’s part of taking care of yourself.",
            "Don’t rush through rest. Let yourself truly relax and recover.",
            "You’re allowed to feel tired. Take it easy and restore your strength.",
            "Remember, rest is an important part of success and well-being.",
            "Your body and mind will thank you for the rest you take today.",
            "Prioritize rest so you can show up as your best self later.",
            "A little rest now will help you move mountains tomorrow.",
            "Sometimes all you need is a bit of quiet to find your energy again.",
            "Rest is productive; it’s how you regain strength for the days ahead.",
            "Trust that it’s okay to step back. Your well-being is worth it.",
            "Take a breath, relax, and know you’re giving yourself what you need."        
        ]
    };

    // Select a random message from the appropriate mood category
    const selectedMessages = motivationalMessages[mood];
    const randomIndex = Math.floor(Math.random() * selectedMessages.length);
    const message = selectedMessages[randomIndex];

    // Update the advice section with the motivational message
    adviceMessage.textContent = message;
    adviceSection.style.display = "block";

    // Scroll to the message
    adviceSection.scrollIntoView({ behavior: "smooth" });
}
